FROM tensorflow/tensorflow:2.16.2-gpu

ENV PYTHONUNBUFFERED=TRUE \
    PYTHONDONTWRITEBYTECODE=TRUE \
    TZ="Asia/Tokyo" \
    LANG=ja_JP.UTF-8 \
    LANGUAGE=ja_JP:en \
    DEBIAN_FRONTEND=noninteractive

RUN pip install --upgrade pip
RUN pip install ray["rllib"] \ 
	tensorflow_probability  \
	tf_keras \
	swig \
	supersuit \
	pettingzoo \
	pyarrow \
	pandas

RUN pip install gymnasium[box2d]

# keras2をデフォルトでつかうように
ENV TF_USE_LEGACY_KERAS=1