FROM rayproject/ray-ml:2.10.0-gpu

ENV PYTHONUNBUFFERED=TRUE \
    PYTHONDONTWRITEBYTECODE=TRUE \
    TZ="Asia/Tokyo" \
    LANG=ja_JP.UTF-8 \
    LANGUAGE=ja_JP:en \
    DEBIAN_FRONTEND=noninteractive

RUN pip install --upgrade pip
RUN pip install \
	#tensorflow_probability  \
	#tf_keras \
	swig
	# ray["rllib"]

RUN pip install gymnasium[box2d]

# keras2をデフォルトでつかうように
# ENV TF_USE_LEGACY_KERAS=1